# Generated by Django 4.0.2 on 2022-02-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finchs',
            new_name='Finch',
        ),
    ]
