# Generated by Django 4.0.2 on 2022-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_state_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='finches',
        ),
        migrations.AddField(
            model_name='state',
            name='finchs',
            field=models.ManyToManyField(related_name='finchs', to='main_app.Finch'),
        ),
    ]
